stages:
  training:
    cmd:
    - python ../../../src/Model_Training/Model_Training.py
    # Publish confusion matrix diff
    - echo "# Multi Class Classification" >> report.md
    - echo "## Plots" >> report.md
    - git add **/train_metric*
    params:
    - test_size
    - epochs
    - mode
    # Hyperparam tuning params
    - hyp_tuning.num_trials
    - hyp_tuning.batch_size
    - hyp_tuning.learning_rate
    - hyp_tuning.activation
    - hyp_tuning.optimizer
    - hyp_tuning.n_layers
    - hyp_tuning.hidden_units
    - hyp_tuning.dropout
    # Training params
    - train.learning_rate
    - train.batch_size
    - train.activation
    - train.optimizer
    - train.n_layers
    - train.hidden_layers
    deps:
    - ../../../src/Model_Training/Model_Training.py
    - Reduced_Features.csv
    outs:
    - keras_model.onnx
    plots:
    - classes.csv:
        template: confusion
        x: actual
        y: predicted
    live:
      train_metric:
        summary: true
        html: false
        cache: false
