stages:
  # feat-corr:
  #   cmd:
  #   - python ../../../src/Feature_Importance/Feature_Correlation.py
  #   deps:
  #   - ../../../src/Feature_Importance/Feature_Correlation.py
  #   - ../../../src/Feature_Importance/utils.py
  #   - Full_Features.csv
  #   outs:
  #   - Non_Correlated_Features.csv
  feat-sel:
    cmd:
    # - pip install -r ../../../src/Feature_Importance/requirements.txt
    - python ../../../src/Feature_Importance/Feature_Importance.py
    params:
    - n_features
    - mode
    deps:
    - ../../../src/Feature_Importance/Feature_Importance.py
    - Full_Features.csv
    - Label.csv
    outs:
    - ../2_Training_Workflow/Selected_Features.csv
    - ../2_Training_Workflow/Reduced_Features.csv
