stages:
  feat-sel:
    cmd:
    # - pip install -r ../../../src/Feature_Importance/requirements.txt
    - python ../../../src/Feature_Importance/Feature_Importance.py
    params:
    - n_features
    - mode
    deps:
    - ../../../src/Feature_Importance/Feature_Importance.py
    - Full_Features.csv
    outs:
    - ../2_Training_Workflow/Selected_Features.csv
    - ../2_Training_Workflow/Reduced_Features.csv
